target = "https://raw.githubusercontent.com/fedi-e2ee/public-key-directory-specification/refs/heads/main/Specification.md#get-api-extensions"

# GET api/extensions
#
# Purpose: Lists the [Auxiliary Data Extensions](#auxiliary-data-extensions) supported by this server.
# 
# An HTTP 200 OK request will contain the following response fields:
# 
# | Response Field | Type     | Remarks                            |
# |----------------|----------|------------------------------------|
# | `!pkd-context` | string   | Domain separation                  |
# | `current-time` | string   | [Timestamp](#timestamps)           |
# | `extensions`   | object[] | Array of objects (see next table)  |
# 
# The `!pkd-context` field will be set to the ASCII string `fedi-e2ee:v1/api/extensions`.
# 
# Each entry in the `extensions` array will contain *at least* each of the following fields:
# 
# | Response Field | Type     | Remarks                                 |
# |----------------|----------|-----------------------------------------|
# | `id`           | string   | Unique.                                 |
# | `version`      | string   | Version identifier. Extension-specific. |
# | `ref`          | string   | URL to extension specification.         |
# 
# Extensions **MAY** include optional additional fields, if necessary, in the above table.
# 
# **Example Response**:
# 
# ```json5
# {
#   "!pkd-context": "fedi-e2ee:v1/api/extensions",
#   "time": "1731080850",
#   "extensions": [
#     {
#       "id": "foo-v1",
#       "version": "1.0.0",
#       "ref": "https://example.com/v1"
#     }
#   ]
# }
# ```

[[spec]]
level = "MAY"
quote = '''
Extensions **MAY** include optional additional fields, if necessary, in the above table.
'''

