target = "https://raw.githubusercontent.com/fedi-e2ee/public-key-directory-specification/refs/heads/main/Specification.md#hostile-nation-state-seeks-to-abuse-right-to-be-forgotten-mechanisms-to-cover-up-an-unlawful-intrusion"

# Hostile nation state seeks to abuse _Right To Be Forgotten_ mechanisms to cover up an unlawful intrusion.
#
# **Status**: Open / Addressable.
# 
# Grace instructs Mallory to perform an active attack against a user, then submits a _Right To Be Forgotten_ request to
# the Public Key Directory to destroy evidence of their human rights violation. For example, Grace instructs Alice to
# launch a [BurnDown then AddKey](#race-condition-between-successful-burndown-and-subsequent-addkey) against Bob, then
# uses social engineering to gain access to Bob's friends to spy on their activity.
# 
# If Grace has also enlisted Yvonne to perform the cover-up, this attack will succeed (as currently written).
# 
# However, it is not without risk: [BurnDowns](#burndown) are meant to be noisy, rare Protocol Messages that should
# trigger immediate skepticism for all parties involved. Although they have some legitimate use (i.e., if a user loses
# access to all their secret keys and devices), they should set off alarm bells for anyone using the Public Key Directory.
# 
# To address this risk, any software building E2EE on top of the Public Key Directory **MUST** immediately demote the
# trust status of any participants that receive a successful BurnDown. At minimum, this means requiring any higher-level
# validation be performed again (e.g., safety number comparison) as if chatting with a stranger.
# 
# Obviously, if Grace is unable to enlist Yvonne, and cannot convince the Public Key Directory operator that the _Right To 
# Be Forgotten_ request is legitimate, then Grace's cover-up will not succeed. However, requiring legal acumen to prevent
# misbehavior is a poor mechanism, so we consider this risk "Open" in this case.

[[spec]]
level = "MUST"
quote = '''
To address this risk, any software building E2EE on top of the Public Key Directory **MUST** immediately demote the
trust status of any participants that receive a successful BurnDown.
'''

