target = "https://raw.githubusercontent.com/fedi-e2ee/public-key-directory-specification/refs/heads/main/Specification.md#key-identifiers"

# Key Identifiers
#
# Every time an `AddKey` message is accepted by the Public Key Directory, the PKD will generate a 256-bit random unique
# `key-id` for that public key. This value is not secret or sensitive in any way, and is only used to point to an existing
# public key to reduce the amount of rejected signatures software must publish.
# 
# Every message except revocations and the first `AddKey` for an Actor **SHOULD** include a `key-id` value.
# Each `key-id` is encoded as an unpadded [base64url](https://datatracker.ietf.org/doc/html/rfc4648#section-5).
# 
# The `key-id` attribute **MUST NOT** be an encoded representation of the public key. The motivation for this restriction
# is to prevent accidental misuse (i.e., someone just decoding the public key from a message and trusting it blindly).
# 
# The `key-id` is not covered in the protocol messages being signed. Instead, it is a hint to the signature validation
# software which public key to select when there is more than one option. Their values are totally arbitrary and, aside
# from uniqueness, serve no other purpose.

[[spec]]
level = "SHOULD"
quote = '''
Every message except revocations and the first `AddKey` for an Actor **SHOULD** include a `key-id` value.
'''

[[spec]]
level = "MUST"
quote = '''
The `key-id` attribute **MUST NOT** be an encoded representation of the public key.
'''

