target = "https://raw.githubusercontent.com/fedi-e2ee/public-key-directory-specification/refs/heads/main/Specification.md#mirror-plaintext-cache-invalidation"

# Mirror Plaintext Cache Invalidation
#
# The replicated ciphertext **MAY** be persisted indefinitely, but regardless of the trust status of a given Mirror, if
# the mirror has access to the plaintext (whether by caching a copy or by `rewrapped-keys`), the Mirror **MUST** 
# occasionally attempt to verify that the source server has not deliberately wiped their copy of the symmetric key. 
# If the source has, the mirror **MUST** do the same.
# 
# When processing a request for a replicated record, checking the status of the upstream record is **RECOMMENDED** if it 
# has not been checked in the past 24 hours.
# 
# If the source is unavailable, the mirror may defer retries for up to 7 days. After this grace period, they should treat 
# the relevant rewrapped keys and cached plaintexts as invalid and remove them. If the source comes back online, the 
# mirror **MAY** re-cache the symmetric keys and/or plaintext.

[[spec]]
level = "MUST"
quote = '''
The replicated ciphertext **MAY** be persisted indefinitely, but regardless of the trust status of a given Mirror, if
the mirror has access to the plaintext (whether by caching a copy or by `rewrapped-keys`), the Mirror **MUST**
occasionally attempt to verify that the source server has not deliberately wiped their copy of the symmetric key.
'''

[[spec]]
level = "MUST"
quote = '''
If the source has, the mirror **MUST** do the same.
'''

[[spec]]
level = "SHOULD"
quote = '''
When processing a request for a replicated record, checking the status of the upstream record is **RECOMMENDED** if it
has not been checked in the past 24 hours.
'''

[[spec]]
level = "MAY"
quote = '''
If the source comes back online, the
mirror **MAY** re-cache the symmetric keys and/or plaintext.
'''

