target = "https://raw.githubusercontent.com/fedi-e2ee/public-key-directory-specification/refs/heads/main/Specification.md#moveidentity"

# MoveIdentity
#
# This moves all the mappings from the old Actor ID to the new Actor ID.
# 
# The message **MUST** be signed by a valid secret key for the `old-actor`, whereas the HTTP Signature **MUST** come from 
# the new Fediverse Server instance. This grants users the ability to move their identity to a new instance, provided they
# can successfully authenticate to the new instance.
# 
# This message **MUST** be rejected if there are existing public keys for the target `new-actor`.

[[spec]]
level = "MUST"
quote = '''
The message **MUST** be signed by a valid secret key for the `old-actor`, whereas the HTTP Signature **MUST** come from
the new Fediverse Server instance.
'''

[[spec]]
level = "MUST"
quote = '''
The message **MUST** be signed by a valid secret key for the `old-actor`, whereas the HTTP Signature **MUST** come from
the new Fediverse Server instance.
'''

[[spec]]
level = "MUST"
quote = '''
This message **MUST** be rejected if there are existing public keys for the target `new-actor`.
'''

