target = "https://raw.githubusercontent.com/fedi-e2ee/public-key-directory-specification/refs/heads/main/Specification.md#trusted-mirrors"

# Trusted Mirrors
#
# If the source Public Key Directory trusts the mirror's operators, the source **MAY** republish the symmetric key used
# to encrypt that Protocol Message's attributes, encrypted using HPKE with the mirror's latest public key (i.e., from
# their most recent Checkpoint). 
# 
# These HPKE-encrypted blobs will be cached and appended to the `rewrapped-keys` field for any record that has not been 
# wiped.
# 
# Key rewrapping is not recommended by default, as it would allow the replica to decrypt the record even if the source PKD
# received a legal take-down notice. Instead, it should only be used for mirrors you trust to respect when the source
# has been wiped by a legal request, and purge their copy of the symmetric key in turn.
# 
# Trusted Mirrors may serve as a form of fail-over in case the source instance is inaccessible, as a mechanism to reduce
# the efficacy of Denial of Service attacks.

[[spec]]
level = "MAY"
quote = '''
If the source Public Key Directory trusts the mirror's operators, the source **MAY** republish the symmetric key used
to encrypt that Protocol Message's attributes, encrypted using HPKE with the mirror's latest public key (i.e., from
their most recent Checkpoint).
'''

