target = "https://raw.githubusercontent.com/fedi-e2ee/public-key-directory-specification/refs/heads/main/Specification.md#witness-co-signing"

# Witness Co-Signing
#
# Sigsum doesn't use a gossip protocol. Instead, it relies on proactive witness co-signatures into other ledgers. See
# [section 3.5 of the Sigsum paper for more details](https://git.glasklar.is/nisse/cats-2023/-/blob/main/sigsum-design-cats-2023.pdf).
# 
# It's not sufficient for Public Key Directory entries to merely validate that a record exists in a Merkle tree. At least
# one witness **MUST** also validate that the current state is deterministically reproducible from the history of the 
# transparency log.
# 
# To provide a mechanism for this requirement, PKDs are encouraged to send [`Checkpoint`](#checkpoint) Protocol Messages
# to their peers in addition to regular Sigsum witness co-signatures.

[[spec]]
level = "MUST"
quote = '''
At least
one witness **MUST** also validate that the current state is deterministically reproducible from the history of the
transparency log.
'''

