[package]
name = "pkd_core"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
base64 = "0.22.1"
base64-url = "3.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
