[package]
name = "pkd_core"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
base64ct = { version = "1.8.0", features = ["alloc"] }
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
